Converting Images into 2D Numpy arrays

In [6]:
from PIL import Image
import numpy as np

# Loading  the image
image = Image.open('1.jpg')
image_array = np.array(image)

# Print the shape of the array and the array itself
print("Shape of the array:", image_array.shape) #will show height , width , and colour channels (RGBA)
print(image_array)

import numpy as np
image_array = np.array(image)

def k_means_image(image_array, k, max_iterations=100):
    # Reshape the 3D image array into a 2D array of pixel values
    data = image_array.reshape(-1, image_array.shape[-1])
    
def k_means_image(image, k, max_iterations=100):
    # Reshape the 2D image array into a 1D array of pixel values
    data = image.reshape(-1, image.shape[-1])
    
    # Step 1: Initialize K cluster centroids randomly
    centroids = data[np.random.choice(data.shape[0], k, replace=False)]
    
    for _ in range(max_iterations):
        # Step 2a: Assign each data point to the nearest centroid
        labels = np.argmin(np.linalg.norm(data[:, np.newaxis] - centroids, axis=2), axis=1)
        
        # Step 2b: Recompute the centroids as the mean of the data points assigned to each centroid
        new_centroids = np.array([data[labels == i].mean(axis=0) for i in range(k)])
        
        # Step 2c: Check for convergence
        if np.allclose(centroids, new_centroids):
            break
        
        centroids = new_centroids
    
    # Reshape centroids back to the image shape
    centroids_image = centroids.reshape((k,) + image.shape[-1:])
    
    return centroids_image, labels.reshape(image.shape[:2])

# Example usag

# Apply K-means clustering to the image
k = 3
centroids_image, labels = k_means_image(image, k)

print("Final centroids image shape:", centroids_image.shape)
print("Cluster assignments shape:", labels.shape)


Shape of the array: (64, 64, 3)
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


AttributeError: 'JpegImageFile' object has no attribute 'reshape'

In [3]:
from PIL import Image
import numpy as np

# Load the black and white image
image = Image.open('path_to_your_image.')

# Convert the image to a NumPy array
image_array = np.array(image)

# Print the shape of the array and the array itself
print("Shape of the array:", image_array.shape)
print(image_array)


Shape of the array: (64, 64, 4)
[[[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 ...

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]

 [[  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]
  ...
  [  0   0   0 255]
  [  0   0   0 255]
  [  0   0   0 255]]]


In [21]:
from PIL import Image
import numpy as np

def k_means_image(image, k, max_iterations=100):
    # Reshape the 3D image array into a 2D array of pixel values
    data = image.reshape(-1, image.shape[-1])
    
    # Step 1: Initialize K cluster centroids randomly
    centroids = data[np.random.choice(data.shape[0], k, replace=False)]
    
    for _ in range(max_iterations):
        # Step 2a: Assign each data point to the nearest centroid
        labels = np.argmin(np.linalg.norm(data[:, np.newaxis] - centroids, axis=2), axis=1)
        
        # Step 2b: Recompute the centroids as the mean of the data points assigned to each centroid
        new_centroids = np.array([data[labels == i].mean(axis=0) if np.sum(labels == i) > 0 else centroids[i] for i in range(k)])
        
        # Step 2c: Check for convergence
        if np.allclose(centroids, new_centroids):
            break
        
        centroids = new_centroids
    
    # Reshape centroids back to the image shape
    centroids_image = centroids.reshape((k,) + image.shape[-1:])
    
    return centroids_image, labels.reshape(image.shape[:2])

# Loading the image
image = Image.open('1.jpg')
image_array = np.array(image)

# Apply K-means clustering to the image
k = 3
centroids_image, labels = k_means_image(image_array, k)

print("Final centroids image shape:", centroids_image.shape)
print("Cluster assignments shape:", labels.shape)

def calculate_distance(p1, p2):
    return np.linalg.norm(p1 - p2)

# Loading the image
image = Image.open('1.jpg')
image_array = np.array(image)

# Apply K-means clustering to the image
k = 3
centroids_image, labels = k_means_image(image_array, k)

# Calculate the center points of each cluster
centers = np.array([centroids_image[i].reshape(-1, centroids_image[i].shape[-1]).mean(axis=0) for i in range(k)])


# Calculate the distances between all pairs of cities (centers)
distances = np.zeros((k, k))
for i in range(k):
    for j in range(i+1, k):
        distance = calculate_distance(centers[i], centers[j])
        distances[i][j] = distance
        distances[j][i] = distance

# Present the distances in a clear format, such as a table
print("Distances between cities (center points of clusters):")
print("\t" + "\t".join(f"City {i+1}" for i in range(k)))
for i in range(k):
    print(f"City {i+1}\t" + "\t".join(f"{distances[i][j]:.2f}" for j in range(k)))

Final centroids image shape: (3, 3)
Cluster assignments shape: (64, 64)
Distances between cities (center points of clusters):
	City 1	City 2	City 3
City 1	0.00	412.67	435.40
City 2	412.67	0.00	22.73
City 3	435.40	22.73	0.00


In [20]:
from PIL import Image
import numpy as np

def k_means_image(image, k, max_iterations=100):
    # Reshape the 3D image array into a 2D array of pixel values
    data = image.reshape(-1, image.shape[-1])
    
    # Step 1: Initialize K cluster centroids randomly
    centroids = data[np.random.choice(data.shape[0], k, replace=False)]
    
    for _ in range(max_iterations):
        # Step 2a: Assign each data point to the nearest centroid
        labels = np.argmin(np.linalg.norm(data[:, np.newaxis] - centroids, axis=2), axis=1)
        
        # Step 2b: Recompute the centroids as the mean of the data points assigned to each centroid
        new_centroids = np.array([data[labels == i].mean(axis=0) if np.sum(labels == i) > 0 else centroids[i] for i in range(k)])
        
        # Step 2c: Check for convergence
        if np.allclose(centroids, new_centroids):
            break
        
        centroids = new_centroids
    
    # Reshape centroids back to the image shape
    centroids_image = centroids.reshape((k,) + image.shape[-1:])
    
    return centroids_image, labels.reshape(image.shape[:2])

# Loading the image
image = Image.open('3.png')
image_array = np.array(image)

# Apply K-means clustering to the image
k = 3
centroids_image, labels = k_means_image(image_array, k)

print("Final centroids image shape:", centroids_image.shape)
print("Cluster assignments shape:", labels.shape)

def calculate_distance(p1, p2):
    return np.linalg.norm(p1 - p2)

# Loading the image
image = Image.open('3.png')
image_array = np.array(image)

# Apply K-means clustering to the image
k = 4
centroids_image, labels = k_means_image(image_array, k)

# Calculate the center points of each cluster
centers = np.array([centroids_image[i].reshape(-1, centroids_image[i].shape[-1]).mean(axis=0) for i in range(k)])


# Calculate the distances between all pairs of cities (centers)
distances = np.zeros((k, k))
for i in range(k):
    for j in range(i+1, k):
        distance = calculate_distance(centers[i], centers[j])
        distances[i][j] = distance
        distances[j][i] = distance

# Present the distances in a clear format, such as a table
print("Distances between cities (center points of clusters):")
print("\t" + "\t".join(f"City {i+1}" for i in range(k)))
for i in range(k):
    print(f"City {i+1}\t" + "\t".join(f"{distances[i][j]:.2f}" for j in range(k)))

Final centroids image shape: (3, 4)
Cluster assignments shape: (64, 64)
Distances between cities (center points of clusters):
	City 1	City 2	City 3	City 4
City 1	0.00	441.67	441.67	441.67
City 2	441.67	0.00	0.00	0.00
City 3	441.67	0.00	0.00	0.00
City 4	441.67	0.00	0.00	0.00
